### ISSUE TITLE
Error setting temperature range and frame rate when attempting to run at 80Hz

### ISSUE THREAD

**Issue by AshleySetter** [nqminds/nqm-irimager#89]
When I attempt to set the camera to a framerate of 80Hz with the an xml file with the following contents:

```
<?xml version="1.0" encoding="UTF-8"?>
<imager xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <videoformatindex>0</videoformatindex> <!-- index of the used video format (USB endpoint) -->
  <formatspath>/usr/share/libirimager</formatspath>
  <calipath>/usr/share/libirimager/cali</calipath>
  <!-- Uncomment the following lines to specify user-defined parameters for the desired optic
       and temperature range. Be aware to specify meaningful parameters.
       See documentation for further information: http://evocortex.com/libirimager2/html/index.html
       By default, the first available optic and the first meaningful temperature range are selected.
  -->
  <fov>25</fov>
  <temperature>
    <min>500</min>
    <max>1800</max>
  </temperature>
  <optics_text></optics_text>
  <framerate>80.0</framerate>             <!-- scaled down frame rate, must be less or equal than camera frame rate -->
  <bispectral>0</bispectral>              <!-- 0=only thermal sensor, 1=bispectral technology (only PI200/PI230) -->
  <average>0</average>                    <!-- average callback frames over intermediate frames -->
  <autoflag>
    <enable>1</enable>
    <mininterval>15.0</mininterval>
    <maxinterval>0.0</maxinterval>
  </autoflag>
  <pif_in_mode>0</pif_in_mode>            <!-- 0=Image capture (default), 1=Flag control -->
  <pif_out_mode>0</pif_out_mode>          <!-- 0=Off (default), 1=Frame sync signal -->
  <pif_out_voltage>5000</pif_out_voltage> <!-- PIF out voltage in mV -->
  <tchipmode>0</tchipmode>                <!-- 0=Floating (default), 1=Auto, 2=Fixed value -->
  <tchipfixedvalue>40.0</tchipfixedvalue> <!-- Fixed value for tchipmode=2 -->
  <focus>50.0</focus> <!-- position of focus motor in % of range [0; 100] -->
</imager>
```

I get the following error:

```
DEBUG:nqm.irimager:Redirecting spdlogs to a callback.
DEBUG:nqm.irimager:set up Python logging callback
DEBUG:nqm.irimager:Making FIFO at /run/user/1002/nqm-irimager/irlogger.fifo_3_5_2024_12-28-47.log for logging
DEBUG:nqm.irimager:starting thread
DEBUG:nqm.irimager:Starting evo::IRLogger to file /run/user/1002/nqm-irimager/irlogger.fifo.some_time
DEBUG:nqm.irimager:Started new thread to read from /run/user/1002/nqm-irimager/irlogger.fifo_3_5_2024_12-28-47.log
Level 5:nqm.irimager:Started evo::IRLogger
WARNING:nqm.irimager:Ignoring error when reading XML file at ../tests/__fixtures__/382x288@80Hz.xml.
DEBUG:nqm.irimager:[IRDeviceParams.cpp:146] Parameters
DEBUG:nqm.irimager:[IRDeviceParams.cpp:147] serial: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:148] videoformatindex: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:149] fov: 25
DEBUG:nqm.irimager:[IRDeviceParams.cpp:150] optics_text: 
DEBUG:nqm.irimager:[IRDeviceParams.cpp:151] formatspath: /usr/share/libirimager
DEBUG:nqm.irimager:[IRDeviceParams.cpp:152] calipath: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[IRDeviceParams.cpp:153] temperature min: 500
DEBUG:nqm.irimager:[IRDeviceParams.cpp:154] temperature max: 1800
DEBUG:nqm.irimager:[IRDeviceParams.cpp:155] framerate: 80
DEBUG:nqm.irimager:[IRDeviceParams.cpp:156] bispectral: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:157] average: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:158] flag automatic: 1
DEBUG:nqm.irimager:[IRDeviceParams.cpp:159] min interval: 15
DEBUG:nqm.irimager:[IRDeviceParams.cpp:160] max interval: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:161] PIF mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:162] chip heating mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:163] chip heating fixed val: 40
DEBUG:nqm.irimager:[IRDeviceParams.cpp:164] focus:  50
INFO:nqm.irimager:[IRDeviceCreate.cpp:23] Searching for attached device...
DEBUG:nqm.irimager:[UdevHelper.cpp:93] Try opening video device /dev/video1 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:25] Instantiated ImagerUVC
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:148] OpenDevice
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:174] Try opening video device /dev/video1 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:207] Stream size: 382 x 290
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:223] Pixelformat: 1448695129, Frequency: 27
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:236] VIDIOC_QUERYCAP successful for PI IMAGER: PI IMAGER
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:78] initMmap
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:110] mmap request: 4 buffers
DEBUG:nqm.irimager:[Cali.cpp:96] Calibration directory path: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[Cali.cpp:97] Calibration file name: Cali-18072010.xml
DEBUG:nqm.irimager:[Cali.cpp:107] Calibration data A: 1450 B:470 C:4095 D:1500
INFO:nqm.irimager:[IRImager.cpp:245] Init thermal imager with size: 382x290@27 Hz
DEBUG:nqm.irimager:[IRImager.cpp:354] Using HID control interface
WARNING:nqm.irimager:[IRImager.cpp:1089] Will not set focus motor pos --> no focus motor
DEBUG:nqm.irimager:[IRImager.cpp:388] Frameconfig - width(in): 382, height(in): 290, interval: 370370, max framerate: 27, HW interval: 0.037037
DEBUG:nqm.irimager:[ImageProcessing.cpp:174] Source buffer size: 221560 Width: 382 Height: 290
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /usr/share/libirimager/Formats.def
DEBUG:nqm.irimager:[OpSource.cpp:560] Format found with size: 382
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /usr/share/libirimager/Formats.def
ERROR:nqm.irimager:[IRImager.cpp:430] Error setting temperature range and frame rate. Check videoformatindex for validity.
```

If you @aloisklink , have any idea of how to debug this, it would be much appreciated.

**Comment by AshleySetter** [comment]
It appears I need to use videoformatindex 1, which causes it to select the calibration data with the matching 80Hz framerate: 

My XML file is then:

```
<?xml version="1.0" encoding="UTF-8"?>
<imager xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <videoformatindex>1</videoformatindex> <!-- index of the used video format (USB endpoint) -->
  <formatspath>/usr/share/libirimager</formatspath>
  <calipath>/usr/share/libirimager/cali</calipath>
  <!-- Uncomment the following lines to specify user-defined parameters for the desired optic
       and temperature range. Be aware to specify meaningful parameters.
       See documentation for further information: http://evocortex.com/libirimager2/html/index.html
       By default, the first available optic and the first meaningful temperature range are selected.
  -->
  <fov>25</fov>
  <temperature>
    <min>500</min>
    <max>1800</max>
  </temperature>
  <optics_text></optics_text>
  <framerate>80.0</framerate>             <!-- scaled down frame rate, must be less or equal than camera frame rate -->
  <bispectral>0</bispectral>              <!-- 0=only thermal sensor, 1=bispectral technology (only PI200/PI230) -->
  <average>0</average>                    <!-- average callback frames over intermediate frames -->
  <autoflag>
    <enable>1</enable>
    <mininterval>15.0</mininterval>
    <maxinterval>0.0</maxinterval>
  </autoflag>
  <pif_in_mode>0</pif_in_mode>            <!-- 0=Image capture (default), 1=Flag control -->
  <pif_out_mode>0</pif_out_mode>          <!-- 0=Off (default), 1=Frame sync signal -->
  <pif_out_voltage>5000</pif_out_voltage> <!-- PIF out voltage in mV -->
  <tchipmode>0</tchipmode>                <!-- 0=Floating (default), 1=Auto, 2=Fixed value -->
  <tchipfixedvalue>40.0</tchipfixedvalue> <!-- Fixed value for tchipmode=2 -->
  <focus>50.0</focus> <!-- position of focus motor in % of range [0; 100] -->
</imager>
```


And output logging is:

```
DEBUG:nqm.irimager:Redirecting spdlogs to a callback.
DEBUG:nqm.irimager:set up Python logging callback
DEBUG:nqm.irimager:Making FIFO at /run/user/1002/nqm-irimager/irlogger.fifo_3_5_2024_13-23-48.log for logging
DEBUG:nqm.irimager:starting thread
DEBUG:nqm.irimager:Starting evo::IRLogger to file /run/user/1002/nqm-irimager/irlogger.fifo.some_time
DEBUG:nqm.irimager:Started new thread to read from /run/user/1002/nqm-irimager/irlogger.fifo_3_5_2024_13-23-48.log
Level 5:nqm.irimager:Started evo::IRLogger
WARNING:nqm.irimager:Ignoring error when reading XML file at ../tests/__fixtures__/382x288@80Hz.xml.
DEBUG:nqm.irimager:[IRDeviceParams.cpp:146] Parameters
DEBUG:nqm.irimager:[IRDeviceParams.cpp:147] serial: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:148] videoformatindex: 1
DEBUG:nqm.irimager:[IRDeviceParams.cpp:149] fov: 25
DEBUG:nqm.irimager:[IRDeviceParams.cpp:150] optics_text: 
DEBUG:nqm.irimager:[IRDeviceParams.cpp:151] formatspath: /usr/share/libirimager
DEBUG:nqm.irimager:[IRDeviceParams.cpp:152] calipath: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[IRDeviceParams.cpp:153] temperature min: 500
DEBUG:nqm.irimager:[IRDeviceParams.cpp:154] temperature max: 1800
DEBUG:nqm.irimager:[IRDeviceParams.cpp:155] framerate: 80
DEBUG:nqm.irimager:[IRDeviceParams.cpp:156] bispectral: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:157] average: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:158] flag automatic: 1
DEBUG:nqm.irimager:[IRDeviceParams.cpp:159] min interval: 15
DEBUG:nqm.irimager:[IRDeviceParams.cpp:160] max interval: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:161] PIF mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:162] chip heating mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:163] chip heating fixed val: 40
DEBUG:nqm.irimager:[IRDeviceParams.cpp:164] focus:  50
INFO:nqm.irimager:[IRDeviceCreate.cpp:23] Searching for attached device...
DEBUG:nqm.irimager:[UdevHelper.cpp:93] Try opening video device /dev/video1 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:25] Instantiated ImagerUVC
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:148] OpenDevice
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:174] Try opening video device /dev/video1 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:207] Stream size: 384 x 288
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:223] Pixelformat: 1448695129, Frequency: 80
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:236] VIDIOC_QUERYCAP successful for PI IMAGER: PI IMAGER
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:78] initMmap
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:110] mmap request: 4 buffers
DEBUG:nqm.irimager:[Cali.cpp:96] Calibration directory path: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[Cali.cpp:97] Calibration file name: Cali-18072010.xml
DEBUG:nqm.irimager:[Cali.cpp:107] Calibration data A: 1450 B:470 C:4095 D:1500
INFO:nqm.irimager:[IRImager.cpp:245] Init thermal imager with size: 384x288@80 Hz
DEBUG:nqm.irimager:[IRImager.cpp:354] Using HID control interface
WARNING:nqm.irimager:[IRImager.cpp:1089] Will not set focus motor pos --> no focus motor
DEBUG:nqm.irimager:[IRImager.cpp:388] Frameconfig - width(in): 384, height(in): 288, interval: 125000, max framerate: 80, HW interval: 0.0125
DEBUG:nqm.irimager:[ImageProcessing.cpp:174] Source buffer size: 221184 Width: 384 Height: 288
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /usr/share/libirimager/Formats.def
DEBUG:nqm.irimager:[OpSource.cpp:560] Format found with size: 13
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /usr/share/libirimager/Formats.def
DEBUG:nqm.irimager:[ImageProcessing.cpp:104] Source buffer size: 221184 Width: 384 Height: 288
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /usr/share/libirimager/Formats.def
DEBUG:nqm.irimager:[OpSource.cpp:560] Format found with size: 13
DEBUG:nqm.irimager:[IRImager.cpp:685] Caught onFrameInit with size: 382x288
DEBUG:nqm.irimager:[OpCorr.cpp:437] Read cali: /usr/share/libirimager/cali/Cali-18072010-25-500-1800-80.dat
DEBUG:nqm.irimager:[ImageProcessing.cpp:911] Update flag temperature: 36.0625
DEBUG:nqm.irimager:[ImageProcessing.cpp:914] Update box temperature: 36.0625
DEBUG:nqm.irimager:[IRImager.cpp:482] Chip heating disabled
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:305] startStreaming
Traceback (most recent call last):
  File "usage_example.py", line 13, in <module>
    with irimager:
RuntimeError: Error occurred in starting stream. You may need to reconnect the camera.
```

I'm unsure what is causing the RuntimeError, as the camera works correctly for the 27Hz config at the moment (both before and after attempting to run with the 80Hz Config).

**Comment by AshleySetter** [comment]
I'm now getting a subtly different error (with the same xml file):

```
DEBUG:nqm.irimager:Redirecting spdlogs to a callback.
DEBUG:nqm.irimager:set up Python logging callback
DEBUG:nqm.irimager:Making FIFO at /run/user/1002/nqm-irimager/irlogger.fifo_7_5_2024_11-23-58.log for logging
DEBUG:nqm.irimager:starting thread
DEBUG:nqm.irimager:Starting evo::IRLogger to file /run/user/1002/nqm-irimager/irlogger.fifo.some_time
DEBUG:nqm.irimager:Started new thread to read from /run/user/1002/nqm-irimager/irlogger.fifo_7_5_2024_11-23-58.log
Level 5:nqm.irimager:Started evo::IRLogger
WARNING:nqm.irimager:Ignoring error when reading XML file at ../tests/__fixtures__/382x288@80Hz.xml.
DEBUG:nqm.irimager:[IRDeviceParams.cpp:146] Parameters
DEBUG:nqm.irimager:[IRDeviceParams.cpp:147] serial: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:148] videoformatindex: 1
DEBUG:nqm.irimager:[IRDeviceParams.cpp:149] fov: 25
DEBUG:nqm.irimager:[IRDeviceParams.cpp:150] optics_text: 
DEBUG:nqm.irimager:[IRDeviceParams.cpp:151] formatspath: /home/ash/nqm-irimager/scripts
DEBUG:nqm.irimager:[IRDeviceParams.cpp:152] calipath: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[IRDeviceParams.cpp:153] temperature min: 500
DEBUG:nqm.irimager:[IRDeviceParams.cpp:154] temperature max: 1800
DEBUG:nqm.irimager:[IRDeviceParams.cpp:155] framerate: 80
DEBUG:nqm.irimager:[IRDeviceParams.cpp:156] bispectral: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:157] average: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:158] flag automatic: 1
DEBUG:nqm.irimager:[IRDeviceParams.cpp:159] min interval: 15
DEBUG:nqm.irimager:[IRDeviceParams.cpp:160] max interval: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:161] PIF mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:162] chip heating mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:163] chip heating fixed val: 40
DEBUG:nqm.irimager:[IRDeviceParams.cpp:164] focus:  50
INFO:nqm.irimager:[IRDeviceCreate.cpp:23] Searching for attached device...
DEBUG:nqm.irimager:[UdevHelper.cpp:93] Try opening video device /dev/video1 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:25] Instantiated ImagerUVC
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:148] OpenDevice
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:174] Try opening video device /dev/video1 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:207] Stream size: 384 x 288
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:223] Pixelformat: 1448695129, Frequency: 80
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:236] VIDIOC_QUERYCAP successful for PI IMAGER: PI IMAGER
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:78] initMmap
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:110] mmap request: 4 buffers
DEBUG:nqm.irimager:[Cali.cpp:96] Calibration directory path: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[Cali.cpp:97] Calibration file name: Cali-18072010.xml
DEBUG:nqm.irimager:[Cali.cpp:107] Calibration data A: 1450 B:470 C:4095 D:1500
INFO:nqm.irimager:[IRImager.cpp:245] Init thermal imager with size: 384x288@80 Hz
DEBUG:nqm.irimager:[IRImager.cpp:354] Using HID control interface
WARNING:nqm.irimager:[IRImager.cpp:1089] Will not set focus motor pos --> no focus motor
DEBUG:nqm.irimager:[IRImager.cpp:388] Frameconfig - width(in): 384, height(in): 288, interval: 125000, max framerate: 80, HW interval: 0.0125
DEBUG:nqm.irimager:[ImageProcessing.cpp:174] Source buffer size: 221184 Width: 384 Height: 288
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /home/ash/nqm-irimager/scripts/Formats.def
DEBUG:nqm.irimager:[OpSource.cpp:560] Format found with size: 13
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /home/ash/nqm-irimager/scripts/Formats.def
DEBUG:nqm.irimager:[ImageProcessing.cpp:104] Source buffer size: 221184 Width: 384 Height: 288
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /home/ash/nqm-irimager/scripts/Formats.def
DEBUG:nqm.irimager:[OpSource.cpp:560] Format found with size: 13
DEBUG:nqm.irimager:[IRImager.cpp:685] Caught onFrameInit with size: 382x288
DEBUG:nqm.irimager:[OpCorr.cpp:437] Read cali: /usr/share/libirimager/cali/Cali-18072010-25-500-1800-80.dat
DEBUG:nqm.irimager:[ImageProcessing.cpp:911] Update flag temperature: 27.6875
DEBUG:nqm.irimager:[ImageProcessing.cpp:914] Update box temperature: 27.6875
DEBUG:nqm.irimager:[IRImager.cpp:482] Chip heating disabled
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:305] startStreaming
Started at 2024-05-07 11:23:59.785896
-79.59248646927729
Traceback (most recent call last):
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:428] Select error
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:366] stopStreaming
  File "usage_example.py", line 19, in <module>
    array, timestamp = irimager.get_frame()
RuntimeError: IRIMAGER_NODATA: Error occurred in getting frame. You may need to reconnect the camera.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "usage_example.py", line 21, in <module>
    except error:
NameError: name 'error' is not defined
```

**Comment by aloisklink** [comment]
> RuntimeError: IRIMAGER_NODATA: Error occurred in getting frame. You may need to reconnect the camera.

Hmmmm, here are the four things that I think might help:

- Try using the following config file, just to confirm it's not an issue with our config file: https://github.com/nqminds/nqm-dream/blob/master/databots/camera-driver-databot/camera-configs/382x288%4080Hz
- Try using a different USB port on a more powerful PC, ideally one connected directly to the CPU, and not via the motherboard's chipset (you'll probably need to look at your motherboard manual for this). It's possible that this is causing latency issues, and I have heard that even USB 2.0 devices can have this issue on modern PCs.
- Try enabling `sudo rmmod uvcvideo; sudo modprobe uvcvideo nodrop=1` if you haven't already. (if it works, and it doesn't seem to be causing any other issues, you can also make it permanent by doing something like `echo 'options uvcvideo nodrop=1' | sudo tee --append '/etc/modprobe.d/uvcvideo.conf'`)
- Try upgrading the `libirimager` version to the latest version. I was using v4.1.1 in this, since it was confirmed working in https://github.com/nqminds/nqm-dream/tree/master/databots/camera-driver-databot, but that version is now pretty old.

If all else fails, it might be worth trying to get https://github.com/nqminds/nqm-dream/tree/master/databots/camera-driver-databot set up on a computer, just to confirm whether it's an issue in this repo's code, or somewhere else, but it'll be a bit of a pain to compile and set up, so it's probably not worth doing until you get all the easy tests out of the way first.

**Comment by AshleySetter** [comment]
Thanks for the suggestions Alois, point 1 didn't make a difference, point 2 is non-trivial for now, as it is with TWI,  but I'll keep it in mind. Enabling your suggstion in Point 3 results in a different error being raised, which is good, more information to go on.

```
DEBUG:nqm.irimager:Redirecting spdlogs to a callback.
DEBUG:nqm.irimager:set up Python logging callback
DEBUG:nqm.irimager:Making FIFO at /run/user/1002/nqm-irimager/irlogger.fifo_8_5_2024_11-49-19.log for logging
DEBUG:nqm.irimager:starting thread
DEBUG:nqm.irimager:Starting evo::IRLogger to file /run/user/1002/nqm-irimager/irlogger.fifo.some_time
DEBUG:nqm.irimager:Started new thread to read from /run/user/1002/nqm-irimager/irlogger.fifo_8_5_2024_11-49-19.log
Level 5:nqm.irimager:Started evo::IRLogger
WARNING:nqm.irimager:Ignoring error when reading XML file at ../tests/__fixtures__/382x288@80Hz.xml.
DEBUG:nqm.irimager:[IRDeviceParams.cpp:146] Parameters
DEBUG:nqm.irimager:[IRDeviceParams.cpp:147] serial: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:148] videoformatindex: 1
DEBUG:nqm.irimager:[IRDeviceParams.cpp:149] fov: 25
DEBUG:nqm.irimager:[IRDeviceParams.cpp:150] optics_text: 
DEBUG:nqm.irimager:[IRDeviceParams.cpp:151] formatspath: /home/ash/nqm-irimager/scripts
DEBUG:nqm.irimager:[IRDeviceParams.cpp:152] calipath: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[IRDeviceParams.cpp:153] temperature min: 500
DEBUG:nqm.irimager:[IRDeviceParams.cpp:154] temperature max: 1800
DEBUG:nqm.irimager:[IRDeviceParams.cpp:155] framerate: 80
DEBUG:nqm.irimager:[IRDeviceParams.cpp:156] bispectral: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:157] average: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:158] flag automatic: 1
DEBUG:nqm.irimager:[IRDeviceParams.cpp:159] min interval: 15
DEBUG:nqm.irimager:[IRDeviceParams.cpp:160] max interval: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:161] PIF mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:162] chip heating mode: 0
DEBUG:nqm.irimager:[IRDeviceParams.cpp:163] chip heating fixed val: 40
DEBUG:nqm.irimager:[IRDeviceParams.cpp:164] focus:  50
INFO:nqm.irimager:[IRDeviceCreate.cpp:23] Searching for attached device...
DEBUG:nqm.irimager:[UdevHelper.cpp:93] Try opening video device /dev/video0 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:25] Instantiated ImagerUVC
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:148] OpenDevice
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:174] Try opening video device /dev/video0 ... success
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:207] Stream size: 384 x 288
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:223] Pixelformat: 1448695129, Frequency: 80
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:236] VIDIOC_QUERYCAP successful for PI IMAGER: PI IMAGER
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:78] initMmap
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:110] mmap request: 4 buffers
DEBUG:nqm.irimager:[Cali.cpp:96] Calibration directory path: /usr/share/libirimager/cali
DEBUG:nqm.irimager:[Cali.cpp:97] Calibration file name: Cali-18072010.xml
DEBUG:nqm.irimager:[Cali.cpp:107] Calibration data A: 1450 B:470 C:4095 D:1500
INFO:nqm.irimager:[IRImager.cpp:245] Init thermal imager with size: 384x288@80 Hz
DEBUG:nqm.irimager:[IRImager.cpp:354] Using HID control interface
WARNING:nqm.irimager:[IRImager.cpp:1089] Will not set focus motor pos --> no focus motor
DEBUG:nqm.irimager:[IRImager.cpp:388] Frameconfig - width(in): 384, height(in): 288, interval: 125000, max framerate: 80, HW interval: 0.0125
DEBUG:nqm.irimager:[ImageProcessing.cpp:174] Source buffer size: 221184 Width: 384 Height: 288
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /home/ash/nqm-irimager/scripts/Formats.def
DEBUG:nqm.irimager:[OpSource.cpp:560] Format found with size: 13
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /home/ash/nqm-irimager/scripts/Formats.def
DEBUG:nqm.irimager:[ImageProcessing.cpp:104] Source buffer size: 221184 Width: 384 Height: 288
DEBUG:nqm.irimager:[OpSource.cpp:331] Using formats path: /home/ash/nqm-irimager/scripts/Formats.def
DEBUG:nqm.irimager:[OpSource.cpp:560] Format found with size: 13
DEBUG:nqm.irimager:[IRImager.cpp:685] Caught onFrameInit with size: 382x288
DEBUG:nqm.irimager:[OpCorr.cpp:437] Read cali: /usr/share/libirimager/cali/Cali-18072010-25-500-1800-80.dat
DEBUG:nqm.irimager:[ImageProcessing.cpp:911] Update flag temperature: 38.875
DEBUG:nqm.irimager:[ImageProcessing.cpp:914] Update box temperature: 38.875
DEBUG:nqm.irimager:[IRImager.cpp:482] Chip heating disabled
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:305] startStreaming
Started at 2024-05-08 11:49:21.103498
Traceback (most recent call last):
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:468] Incomplete frame transmission, bytes: 218880, width: 384, height: 288
  File "usage_example.py", line 19, in <module>
DEBUG:nqm.irimager:[IRDeviceUVC.cpp:366] stopStreaming
    array, timestamp = irimager.get_frame()
RuntimeError: IRIMAGER_NOSYNC: Error occurred in getting frame. You may need to reconnect the camera.
```

**Comment by AshleySetter** [comment]
Turns out the issue is intermittent :facepalm: sometimes it raises the error, sometimes it doesn't. I only discovered when I tried running the configs for other frame-rates available in the [dream repo](https://github.com/nqminds/nqm-dream/tree/master/databots/camera-driver-databot/camera-configs).

**Comment by aloisklink** [comment]
> sometimes it raises the error, sometimes it doesn't

It makes me think it is probably an issue related with the USB hardware, or the CPU is too weak.

If you look at CPU usage while getting the images, and it seems low, then it might be the USB hardware.

If you can get somebody to plug in the camera directly into the device (e.g. without a USB hub), and make sure every other USB device is plugged into a different USB port (for bonus points, look at the motherboard layout to see which USB ports are closest to the CPU, and which are shared). I'm sure there's probably also some Linux kernel flags you can modify to make USB more responsive too (e.g. you could increase the [niceness](https://en.wikipedia.org/wiki/Nice_(Unix)) of the process).
